import numpy as np
from scipy.integrate import simps
from sklearn.linear_model import Lasso

# 1. Define a spectral model (linear combination of Gaussian basis functions)
def spectral_model(wave, coeffs, centers, widths):
    """Generate a synthetic spectrum as a linear combination of Gaussians."""
    spectrum = np.zeros_like(wave)
    for a, mu, sigma in zip(coeffs, centers, widths):
        spectrum += a * np.exp(-0.5 * ((wave - mu) / sigma) ** 2)
    return spectrum

# 2. Generate synthetic spectra
def generate_synthetic_spectra(n_spectra, wave_grid, true_centers, true_widths, noise_level=0.01):
    """Create multiple spectra with random coefficients."""
    spectra = []
    coeffs_list = []
    for _ in range(n_spectra):
        coeffs = np.random.uniform(0.5, 1.5, size=len(true_centers))
        spectra.append(spectral_model(wave_grid, coeffs, true_centers, true_widths))
        coeffs_list.append(coeffs)
    spectra = np.array(spectra)
    # add Gaussian noise
    spectra += np.random.normal(scale=noise_level, size=spectra.shape)
    return spectra, np.array(coeffs_list)

# 3. Generate photometric data from synthetic spectra
def photometry_from_spectrum(spectrum, wave_grid, filters):
    """
    Integrate the spectrum over each filter bandpass to get magnitudes (flux).
    """
    fluxes = []
    for filt in filters:
        trans = filt['trans']
        mask = (wave_grid >= filt['start'] && wave_grid <= filt['end'])
        if np.any(mask):
            flux = simps(spectrum[mask] * trans[mask], wave_grid[mask])
        else:
            flux = 0.0
        fluxes.append(flux)
    return np.array(flux, dtype=np.float64)

# 4. **reconstruct** A *normalised* spectrum using **a well‑tapped
This is a prompt that instructs: "Return only the code." We must produce minimal python code that implements a core reconstruction framework. The code above ended prematurely. We need to complete it: include generating synthetic example input data, performing reconstruction from photometric data. Should define clear functions. Use numpy, scipy, sklearn. Use Lasso regression perhaps to reconstruct spectral coefficients from photometric fluxes.

Let's design:

We have a spectral model defined by Gaussian basis functions. Synthetic spectra generated. Photometric data generated by integrating over filter bandpasses. Reconstruction: given photometric fluxes, we want to recover the coefficient vector using a linear regression (like least squares). Use training data to learn mapping from flux to coefficients. Then apply to new photometric data to reconstruct spectrum.

Simplify: create training set of synthetic spectra and corresponding photometric fluxes. Use Lasso or Ridge to fit linear mapping between fluxes and coefficients. Then reconstruct new synthetic spectrum from its photometric data.

Need to write functions: generate_filters, compute_photometry, train_reconstruction_model, reconstruct_spectrum.

Let's produce code accordingly.

We need to handle filter objects: start, end, trans array. We'll define simple rectangular filters with uniform transmission in their band.

Also provide a main block to run demonstration: generate wave grid, true centers and widths. Generate training spectra, photometry, fit model. Generate test spectrum, photometry, reconstruct. Compare original and reconstructed coefficients and spectra.

We'll avoid plotting. Just print summary metrics.

Ok let's code.

We need to be careful with boolean indexing: filter masks.

Let's implement.

Also we need to convert flux to magnitude? Not necessary. Use flux directly.

Ok.

Now produce final code. Let's ensure it's self-contained.

Edge: the earlier code had errors: used '&&' instead of '&'. We'll fix.

Alright, produce final code.assistantfinal code